### ISSUE TITLE
Coinbase UTXO with 0 value makes coinselect fail

### ISSUE THREAD

**Issue by louneskmt** [bitcoinerlab/coinselect#6]
Hey,

My regtest has had the 32 halvings already so the subsidy is now 0, and that makes `coinselect` fail the input validation with `Input value 0 not supported`.

```shell
$ bitcoin-cli gettxout 832d2ca626b7305094f5139883d233ec6e94d5adbc49a8be3c820a7c0848320e 0
{
  "bestblock": "5fd76fd9cda9efdbba534c02c9548bf32bab91e94c2a34ee90ca6b141fa36679",
  "confirmations": 9283,
  "value": 0.00000000,
  "scriptPubKey": {
    "asm": "0 b5123257f2755034498cb39ee694147b59ad07f0",
    "desc": "addr(bcrt1qk5fry4ljw4grgjvvkw0wd9q50dv66plsvx6rxu)#wdfpukwa",
    "hex": "0014b5123257f2755034498cb39ee694147b59ad07f0",
    "address": "bcrt1qk5fry4ljw4grgjvvkw0wd9q50dv66plsvx6rxu",
    "type": "witness_v0_keyhash"
  },
  "coinbase": true
}
```

We have some time before facing this issue in prod, but we might want to remove this specific validation and just don't select UTXOs with a zero value?

**Comment by landabaso** [comment]
Please check if latest version 1.2.1 already addresses your issue. See https://github.com/bitcoinerlab/coinselect/pull/5.

**Comment by louneskmt** [comment]
Oops, thanks!
